server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: media-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/media/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**  # Assuming the endpoint is /api/products
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: user-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**